import React from "react"
import Plumbingimg from "/Users/student/dev/React-apps/Module4/react-roto-router/src/tian-kuan-9AxFJaNySB8-unsplash.jpg"

export default function Home(){ 
    return ( 
        <div className="container">
            <h1 className = "title">React Router Plumbing!</h1>
            <br></br>
            {/* <img alt="Plumbing" src= {Plumbingimg}></img> */}
            <p className = "body-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At varius vel pharetra vel. Tortor pretium       viverra suspendisse potenti. Scelerisque varius morbi enim nunc faucibus a pellentesque. Tortor condimentum lacinia quis vel eros donec ac odio. Nulla porttitor massa id neque aliquam            vestibulum. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ipsum faucibus vitae aliquet nec ullamcorper. At consectetur lorem donec massa. Vitae nunc sed velit dignissim              sodales ut eu sem integer. Diam phasellus vestibulum lorem sed risus ultricies. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Lacinia at quis risus sed vulputate         odio ut. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Nunc sed id semper risus in. Aliquam sem et tortor consequat id. Nunc sed augue lacus viverra vitae       congue eu. Tristique nulla aliquet enim tortor.<br></br>
                Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Ut consequat semper viverra nam libero. Amet tellus cras adipiscing enim. Vel pharetra vel turpis       nunc eget lorem dolor sed viverra. Nisl condimentum id venenatis a. Massa placerat duis ultricies lacus sed turpis. Praesent elementum facilisis leo vel fringilla est. Arcu cursus euismod        quis viverra nibh cras pulvinar mattis. Tellus cras adipiscing enim eu turpis egestas pretium. Urna duis convallis convallis tellus. Elementum integer enim neque volutpat ac. Mauris a diam       maecenas sed enim ut sem viverra aliquet. Netus et malesuada fames ac. Donec pretium vulputate sapien nec sagittis. Ut enim blandit volutpat maecenas volutpat. Ornare arcu dui vivamus        arcu felis. Pellentesque nec nam aliquam sem et tortor. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Eget est lorem ipsum dolor sit amet consectetur                 adipiscing. Dui ut ornare lectus sit amet.

                Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Magna etiam tempor orci eu lobortis. Curabitur vitae nunc sed velit dignissim sodales ut. Neque viverra justo nec ultrices. Congue eu consequat ac felis donec et odio pellentesque diam. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. In eu mi bibendum neque egestas congue. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Magna etiam tempor orci eu lobortis.

                Ultrices sagittis orci a scelerisque purus semper eget duis. Eget sit amet tellus cras adipiscing enim. Mattis rhoncus urna neque viverra justo. Et netus et malesuada fames ac turpis egestas sed. Aliquet eget sit amet tellus. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Scelerisque eu ultrices vitae auctor eu augue ut. At augue eget arcu dictum varius duis at consectetur lorem. Facilisi etiam dignissim diam quis enim lobortis. Orci phasellus egestas tellus rutrum. Habitasse platea dictumst quisque sagittis. Pharetra sit amet aliquam id. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Sapien et ligula ullamcorper malesuada proin libero.

                Tincidunt augue interdum velit euismod. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Senectus et netus et malesuada. Sed nisi lacus sed viverra. Non tellus orci ac auctor. Ornare suspendisse sed nisi lacus sed viverra. Ut sem viverra aliquet eget sit. Gravida arcu ac tortor dignissim convallis aenean et. Elementum sagittis vitae et leo duis. A cras semper auctor neque. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Malesuada nunc vel risus commodo. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Hendrerit dolor magna eget est lorem. Facilisis gravida neque convallis a cras semper auctor neque vitae. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Ipsum suspendisse ultrices gravida dictum fusce ut.</p>
            <div className="left-column"></div>
            <div className = "right-column"></div>
    </div>
    )
}